### ISSUE TITLE
Glossary component - next steps and component adoption process

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds-proposals#40]
@jaclinec and I will work towards creating a next step in the glossary component proposal. We have done a Phase 1 assessment, [research is located here](https://docs.google.com/document/d/1pq5-Cvyi7bkeAVuanyDlgnx8Yh3ziZ7yG8t9n2EiVHo/edit?usp=sharing).

**Tasks:**

- [x] Perform accessibility audit of existing federal solutions to glossary to narrow scope of our proposal. [List of examples is here](https://docs.google.com/document/d/1pq5-Cvyi7bkeAVuanyDlgnx8Yh3ziZ7yG8t9n2EiVHo/edit?usp=sharing).
- [x] Finish preliminary evaluation; draft "when to use, when to consider something else."
- [x] Write the glossary proposal.
- [ ] Establish a public location for component proposals and research.
- [ ] Create next steps for moving forward with the glossary. Steps could include testing existing glossaries with users and wireframing solutions to hand off to the dev team.
- [ ] establish a communications draft to get back to the public on approval (or not) of component
- [ ] include potential PM involvement
